---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration-external
  namespace: control
data:
  ssl-protocols: TLSv1.2
  proxy-connect-timeout: "300"
  proxy-read-timeout: "1200"
  proxy-send-timeout: "300"
  use-http2: "false"
  worker-processes: "24"
  worker-connections: "100000"
  worker-rlimit-nofile: "102400"
  worker-cpu-affinity: "auto"
  keepalive: "200"
  hsts-preload: "true"
  hsts-max-age: "31536000"
  proxy-buffer-size: "256k"
  client-body-buffer-size: "256k"
  ssl-buffer-size: "32k"
  proxy-body-size: "100m"
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: stakater-control-external-ingress
  namespace: control
spec:
  releaseName: stakater-control-external-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com 
    name: nginx-ingress
    version: 1.30.3
  values:
    nameOverride: stakater-control-external
    fullnameOverride: stakater-control-external
    revisionHistoryLimit: 3
    controller:
      name: nginx-ingress
      publishService:
        enabled: true
        pathOverride: "control/stakater-control-external-nginx-ingress"
      ingressClass: external-ingress
      metrics:
        enabled: "true"
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
      config:
        use-proxy-protocol: "false"
        enable-opentracing: "false"
      replicaCount: 2
      podAnnotations: 
        scheduler.alpha.kubernetes.io/critical-pod: "true"
      image:  
        pullPolicy: Always      
      extraArgs:
        configmap: control/nginx-configuration-external
        annotations-prefix: ingress.kubernetes.io     
        default-ssl-certificate: "control/tls-cert" 
        enable-ssl-chain-completion: true
        enable-dynamic-certificates: "false"
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi